POST http://localhost:4000/pacientes
Content-Type: application/json

{
  "nombre": "Hook",
  "propietario": "Ernesto",
  "fecha": "2020-06-01",
  "hora": "10:00",
  "sintomas": "Mareos"
}

###
GET http://localhost:4000/pacientes

###
GET http://localhost:4000/pacientes/5ecccae75763a0fa8d8e391d

###
DELETE http://localhost:4000/pacientes/5ecdc2eb0076672d02d6f706

###
PUT http://localhost:4000/pacientes/5ecccb405763a0fa8d8e391e
Content-Type: application/json

{
  "nombre": "Chuchita",
  "propietario": "Alexa",
  "fecha": "2020-06-01",
  "hora": "09:30",
  "sintomas": "Dolor de cabeza"
}

###
PUT http://localhost:4000/usuarios/5ed34546470f8a1cfabd83fb
Content-Type: application/json

{
  "nombreRealUsario": "Ernesto Darge",
  "emailUsuario": "dargarfal@gmail.com",
  "passUsuario": "cubasoltravel.com",
  "fotoUsario": "./public/img/usuarios/ernest.jpg",
  "creadoUsuario": "2020-05-31",
  "rolUsuario": "administrador"
}

###
POST http://localhost:4000/usuarios
Content-Type: application/json

{
  "nombreRealUsario": "Graciela Falcon",
  "emailUsuario": "graciela@gmail.com",
  "passUsuario": "123",
  "fotoUsario": "./public/img/usuarios/graciela.jpg",
  "rolUsuario": "administrador"
}